language: android
dist: trusty
android:
  components:
    - build-tools-30.0.1
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew test

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
