language: android
dist: trusty
android:
  components:
    - build-tools-30.0.3
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew test

jdk:
  - oraclejdk11
