language: android
dist: trusty
android:
  components:
    - build-tools-30.0.0
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-30
before_script:
  - ./gradlew tasks

script:
  - ./gradlew build check

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
